uv run --no-project --with httpx python harness/llm_arm.py --model deepseek/deepseek-v4-flash --host 'OpenInference' --contract schema --schema S1-home --items frontier/selection_items_home.jsonl --out frontier/stage/deepseek__deepseek-v4-flash__schema__home.jsonl --conc 4 --reasoning off
uv run --no-project --with httpx python harness/llm_arm.py --model deepseek/deepseek-v4-flash --host 'OpenInference' --contract schema --schema S1-desk --items frontier/selection_items_desk.jsonl --out frontier/stage/deepseek__deepseek-v4-flash__schema__desk.jsonl --conc 4 --reasoning off
uv run --no-project --with httpx python harness/llm_arm.py --model deepseek/deepseek-v4-flash --host 'OpenInference' --contract native --schema S1-home --items frontier/selection_items_home.jsonl --out frontier/stage/deepseek__deepseek-v4-flash__native__home.jsonl --conc 4 --reasoning off
uv run --no-project --with httpx python harness/llm_arm.py --model deepseek/deepseek-v4-flash --host 'OpenInference' --contract native --schema S1-desk --items frontier/selection_items_desk.jsonl --out frontier/stage/deepseek__deepseek-v4-flash__native__desk.jsonl --conc 4 --reasoning off
uv run --no-project --with httpx python harness/llm_arm.py --model deepseek/deepseek-v4-flash-0731 --host 'Sail Research' --contract schema --schema S1-home --items frontier/selection_items_home.jsonl --out frontier/stage/deepseek__deepseek-v4-flash-0731__schema__home.jsonl --conc 4 --reasoning off
uv run --no-project --with httpx python harness/llm_arm.py --model deepseek/deepseek-v4-flash-0731 --host 'Sail Research' --contract schema --schema S1-desk --items frontier/selection_items_desk.jsonl --out frontier/stage/deepseek__deepseek-v4-flash-0731__schema__desk.jsonl --conc 4 --reasoning off
uv run --no-project --with httpx python harness/llm_arm.py --model deepseek/deepseek-v4-flash-0731 --host 'Sail Research' --contract native --schema S1-home --items frontier/selection_items_home.jsonl --out frontier/stage/deepseek__deepseek-v4-flash-0731__native__home.jsonl --conc 4 --reasoning off
uv run --no-project --with httpx python harness/llm_arm.py --model deepseek/deepseek-v4-flash-0731 --host 'Sail Research' --contract native --schema S1-desk --items frontier/selection_items_desk.jsonl --out frontier/stage/deepseek__deepseek-v4-flash-0731__native__desk.jsonl --conc 4 --reasoning off
uv run --no-project --with httpx python harness/llm_arm.py --model google/gemma-4-26b-a4b-it --host 'DekaLLM' --contract native --schema S1-home --items frontier/selection_items_home.jsonl --out frontier/stage/google__gemma-4-26b-a4b-it__native__home.jsonl --conc 4 --reasoning off
uv run --no-project --with httpx python harness/llm_arm.py --model google/gemma-4-26b-a4b-it --host 'DekaLLM' --contract native --schema S1-desk --items frontier/selection_items_desk.jsonl --out frontier/stage/google__gemma-4-26b-a4b-it__native__desk.jsonl --conc 4 --reasoning off
uv run --no-project --with httpx python harness/llm_arm.py --model inclusionai/ling-3.0-flash --host 'Novita' --contract native --schema S1-home --items frontier/selection_items_home.jsonl --out frontier/stage/inclusionai__ling-3.0-flash__native__home.jsonl --conc 4 --reasoning off
uv run --no-project --with httpx python harness/llm_arm.py --model inclusionai/ling-3.0-flash --host 'Novita' --contract native --schema S1-desk --items frontier/selection_items_desk.jsonl --out frontier/stage/inclusionai__ling-3.0-flash__native__desk.jsonl --conc 4 --reasoning off
uv run --no-project --with httpx python harness/llm_arm.py --model nvidia/nemotron-3.5-lightning --host 'Phala' --contract schema --schema S1-home --items frontier/selection_items_home.jsonl --out frontier/stage/nvidia__nemotron-3.5-lightning__schema__home.jsonl --conc 4 --reasoning off
uv run --no-project --with httpx python harness/llm_arm.py --model nvidia/nemotron-3.5-lightning --host 'Phala' --contract schema --schema S1-desk --items frontier/selection_items_desk.jsonl --out frontier/stage/nvidia__nemotron-3.5-lightning__schema__desk.jsonl --conc 4 --reasoning off
uv run --no-project --with httpx python harness/llm_arm.py --model nvidia/nemotron-3.5-lightning --host 'Phala' --contract native --schema S1-home --items frontier/selection_items_home.jsonl --out frontier/stage/nvidia__nemotron-3.5-lightning__native__home.jsonl --conc 4 --reasoning off
uv run --no-project --with httpx python harness/llm_arm.py --model nvidia/nemotron-3.5-lightning --host 'Phala' --contract native --schema S1-desk --items frontier/selection_items_desk.jsonl --out frontier/stage/nvidia__nemotron-3.5-lightning__native__desk.jsonl --conc 4 --reasoning off
